version: '3.8'

services:
  web:
    build: ./auth
    command: uvicorn app:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8000:80"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: